language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ymdarake/react-container-template -f Dockerfile.dev .

script:
  - docker run -e CI=true ymdarake/react-container-template npm run test
